services:
  # monolith-frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   environment:
  #     - VITE_API_URL=http://localhost:5000/api
  #   depends_on:
  #     - auth-service

  frontend:
    image: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - user-service
      - card-service
      - transactions-service
    environment:
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=5000
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=5003
      - CARD_SERVICE_HOST=card-service
      - CARD_SERVICE_PORT=5001
      - TRANSACTIONS_SERVICE_HOST=transactions-service
      - TRANSACTIONS_SERVICE_PORT=5002
        #      - VITE_API_URL=http://auth-service:5000/api

  card-service:
    build:
      context: ./backend/card-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aumsvault
      - AUTH_SERVICE_URL=http://auth-service:5000
    depends_on:
      - auth-service
      - db

  transactions-service:
    build:
      context: ./backend/transaction-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aumsvault
      - AUTH_SERVICE_URL=http://auth-service:5000
    depends_on:
      - auth-service
      - db

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
      - AUTH_SERVICE_URL=http://auth-service:5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aumsvault
    depends_on:
      - db
      - auth-service

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aumsvault
      - JWT_SECRET=your-secret-key-change-in-production
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - db

  # monolith-backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/aumsvault
  #     - JWT_SECRET=your-secret-key-change-in-production
  #     - NODE_ENV=production
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aumsvault
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
