apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
  labels:
    app: frontend
spec:
  type: ClusterIP  # Or LoadBalancer if direct external access is needed
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

