apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  namespace: production
  labels:
    app: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
        - name: card-service
          image: card-service:latest  
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: card-service-config
          readinessProbe:
            httpGet:
              path: /health  
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20

