apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  namespace: production
  labels:
    app: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
        - name: card-service
          image: 627720351262.dkr.ecr.us-east-1.amazonaws.com/aumsvault/card-service:v1 
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: card-service-config
