apiVersion: v1
kind: Service
metadata:
  name: card-service
  namespace: production
  labels:
    app: card-service
spec:
  type: ClusterIP  
  selector:
    app: card-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

