apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: production
  labels:
    app: db
spec:
  type: ExternalName
  externalName: <on-prem-db-hostname>  # Replace with the hostname or IP of the on-premises database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

