apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  namespace: production
  labels:
    app: transactions-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
        - name: transactions-service
          image: patelaum/vaultify-transaction-service:v1
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: transactions-service-config
