apiVersion: v1
kind: Service
metadata:
  name: transactions-service
  namespace: production
  labels:
    app: transactions-service
spec:
  type: ClusterIP  
  selector:
    app: transactions-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

