apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
        - name: card-service
          image: your-card-service-image
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
