apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  type: ClusterIP  
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003

