apiVersion: v1
kind: Service
metadata:
  name: on-prem-db
  namespace: database
  labels:
    app: on-prem-db
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: NodePort
  selector:
    app: on-prem-db
  ports:
    - nodePort: 31657
      protocol: TCP
      port: 5432
      targetPort: 5432

