apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: database
  labels:
    app: adminer
spec:
  type: NodePort  
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080  

