# minikube-config.yaml (apply on minikube cluster)
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
    networkName: network2
    meshNetworks:
      network1:
        endpoints:
        - fromRegistry: cluster1
        gateways:
        - address: 10.0.0.1
          port: 15443
      network2:
        endpoints:
        - fromRegistry: cluster2
        gateways:
        - address: 10.0.0.2
          port: 15443
---
# gateway-service.yaml (apply on both clusters)
apiVersion: v1
kind: Service
metadata:
  name: eastwest-gateway
  namespace: istio-system
spec:
  type: NodePort
  ports:
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: eastwestgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eastwest-gateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: eastwestgateway
  template:
    metadata:
      annotations:
        ambient.istio.io/gateway: "true"
      labels:
        app: istio-ingressgateway
        istio: eastwestgateway
    spec:
      containers:
      - name: istio-proxy
        image: auto
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: "sni-dnat"
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: "*"
        ports:
        - containerPort: 15443
          protocol: TCP
